const CHANGE_GAME_STATE = 'CHANGE_GAME_STATE';
const HANDLE_WORD_PRESS = 'HANDLE_WORD_PRESS';
const WAIT_FOR_USER_PRESS = 'WAIT_FOR_USER_PRESS';
const END_GAME = 'END_GAME';
const CHANGE_USER_INFO = 'CHANGE_USER_INFO';

export {
	CHANGE_GAME_STATE,
	HANDLE_WORD_PRESS,
	WAIT_FOR_USER_PRESS,
	END_GAME,
	CHANGE_USER_INFO
};
